<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\jaytwo.HashSiphon\jaytwo.HashSiphon.csproj" />
  </ItemGroup>

</Project>
